/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#ffffff",
        "surface-dim": "#f8f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f9fc",
        "surface-container": "#f1f0fb",
        "surface-container-high": "#ede9fe",
        "surface-container-highest": "#ddd6fe",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        outline: "#e2e8f0",
        "outline-variant": "#e2e8f0",
        primary: "#7e22ce",
        "on-primary": "#ffffff",
        "primary-container": "#7e22ce",
        "on-primary-container": "#ffffff",
        "primary-fixed": "#ede9fe",
        "on-primary-fixed": "#3b0764",
        "primary-fixed-dim": "#ddd6fe",
        "inverse-primary": "#c4b5fd",
        secondary: "#6d28d9",
        "on-secondary": "#ffffff",
        background: "#ffffff",
        "on-background": "#0f172a",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-padding-desktop": "120px",
        "section-padding-mobile": "64px",
        base: "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "display-hero": ["Syne", "sans-serif"],
        "display-hero-mobile": ["Syne", "sans-serif"],
        "headline-lg": ["Syne", "sans-serif"],
        "headline-lg-mobile": ["Syne", "sans-serif"],
        "headline-md": ["Syne", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "body-md": ["Outfit", "sans-serif"],
        "label-sm": ["Outfit", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-hero-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.65", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
        "out-quart": "cubic-bezier(0.165, 0.84, 0.44, 1)",
        "in-out-expo": "cubic-bezier(0.87, 0, 0.13, 1)",
        "spring": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "glass": "cubic-bezier(0.23, 1, 0.32, 1)",
      },
      transitionDuration: {
        "400": "400ms",
        "600": "600ms",
        "800": "800ms",
      },
    },
  },
};
